const formEl = document.querySelector('form');
const playersList = document.querySelector('.players-list');
const inputEl = document.querySelector('.name');
const messageEl = document.querySelector('.message');

// String conversion to array
export const stringToArr = str => str.split(',');

// Removing trailing spaces
export const trimmed = arr => arr.map(el => el.trim());

// Checking if array contains even elements number
export const checkIfEven = arr => arr.length % 2 === 0;

// Generating random integer in range of array length
export const randInt = (arr) => {
  return Math.floor(Math.random()*arr.length)
}

// Creating an array using indexes generated by randInt
export const createRandomArr = (arr) => {
  const newArr = [];
  const arrCopy = [...arr];
  while(arrCopy.length > 0) {
    let index = randInt(arrCopy);
    const person = arrCopy.splice(index, 1).toString();
    newArr.push(person);
  }
  return newArr;
};

// Creating array of arrays containing pairs
export const createPairs = (arr) => {
  let pairs = [];
  const chunk = 2;
  for(let i=0; i < arr.length; i += chunk) {
    pairs.push(arr.slice(i, i + chunk));
  }
  return pairs;
}

// Generating HTML with players pairs
export const buildPairsList = (players, parent) => {
  console.log(players);
  const html = `
  ${players.map(player => `<tr><td>${player[0]}</td><td>:</td><td>${player[1]}</td></tr>`).join("")}
  `
  console.log(html);
  parent.innerHTML = html;
}

export const submitHandler = event => {
  event.preventDefault();
  if(inputEl.value === "") {
    messageEl.textContent = "Podaj imiona zawodników"
  } else {
    messageEl.textContent = "";
    const str = inputEl.value;
    const strArr = stringToArr(str);
    const trimmedArr = trimmed(strArr);
    const checkEven = checkIfEven(trimmedArr);
    if(!checkEven) {
      messageEl.textContent = "Podano nieparzystą liczbę osób, dodaj kogoś jeszcze.)."
      return;
    }
    inputEl.value = "";
    const randomArr = createRandomArr(trimmedArr);
    const players = createPairs(randomArr);
    buildPairsList(players, playersList);
  }
}

formEl?.addEventListener('submit', submitHandler)
