const playersList = document.querySelector('.players-list');
const formEl = document.querySelector('form');
const inputEl = document.querySelector('.name');
const messageEl = document.querySelector('.message');

// String conversion to array
export const stringToArr = str => str.split(',');

// Removing trailing spaces
export const trimmed = arr => arr.map(el => el.trim());

// Checking if array contains even elements number
export const checkIfEven = arr => arr.length % 2 === 0;

// Generating random integer in range of array length
export const randInt = (arr) => {
  return Math.floor(Math.random()*arr.length)
}

// Creating an array using indexes generated by randInt
export const createRandomArr = (arr) => {
  const newArr = [];
  const arrCopy = [...arr];
  while(arrCopy.length > 0) {
    let index = randInt(arrCopy);
    const person = arrCopy.splice(index, 1).toString();
    newArr.push(person);
  }
  return newArr;
};

// Creating array of arrays containing pairs
export const createPairs = (arr) => {
  let pairs = [];
  const chunk = 2;
  for(let i=0; i < arr.length; i += chunk) {
    pairs.push(arr.slice(i, i + chunk));
  }
  return pairs;
}

export const buildPairsList = (players, parent) => {
  players.forEach(el => {
    const listItem = document.createElement('li');
    listItem.textContent = `${el[0]} : ${el[1]}`;
    parent.appendChild(listItem);
  })
  return parent;
}

export const submitHandler = event => {
  event.preventDefault();
  console.log(inputEl.value.length)
  if(inputEl.value === "") {
    messageEl.textContent = "Podaj imiona zawodników"
  } else {
    console.log('test')
    messageEl.textContent = "";
    const str = inputEl.value;
    const strArr = stringToArr(str);
    const trimmedArr = trimmed(strArr);
    const checkEven = checkIfEven(trimmedArr);
    if(!checkEven) {
      messageEl.textContent = "Podano nieparzystą liczbę osób, dodaj kogoś jeszcze.)."
      return;
    }
    inputEl.value = "";
    const randomArr = createRandomArr(trimmedArr);
    const players = createPairs(randomArr);
    buildPairsList(players, playersList);
  }
}


formEl?.addEventListener('submit', submitHandler)